version: '3.9'

services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=db_test
      - POSTGRES_USER=luis
      - POSTGRES_PASSWORD=admin
    ports:
      - 5435:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80